// v67: remove any previous service worker/cache that could keep an old app version alive.
(async()=>{try{if('serviceWorker' in navigator){const regs=await navigator.serviceWorker.getRegistrations();for(const r of regs)await r.unregister();}if('caches' in window){const keys=await caches.keys();for(const k of keys)await caches.delete(k);}}catch(e){}})();
const DAYS=['PONDĚLÍ','ÚTERÝ','STŘEDA','ČTVRTEK','PÁTEK','SOBOTA','NEDĚLE'];
const KEY='mujTreninkPWA_v1';
const defaults=[
 [{name:'Leg Press',sets:3,pauseValue:2,pauseUnit:'min'},{name:'Chest Press',sets:4,pauseValue:2,pauseUnit:'min'},{name:'Stahování kladky',sets:4,pauseValue:2,pauseUnit:'min'}],
 [],
 [{name:'Veslování',sets:4,pauseValue:2,pauseUnit:'min'},{name:'Pec Deck',sets:3,pauseValue:2,pauseUnit:'min'},{name:'Zakopávání',sets:3,pauseValue:2,pauseUnit:'min'}],
 [],
 [{name:'Leg Press',sets:3,pauseValue:2,pauseUnit:'min'},{name:'Chest Press',sets:3,pauseValue:2,pauseUnit:'min'},{name:'Biceps',sets:3,pauseValue:1,pauseUnit:'min'}],[],[]
];
let state=load();
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)); if(x){x.plans=x.plans||clone(defaults);x.history=x.history||{};x.dark=!!x.dark;x.timerEnabled=x.timerEnabled!==false;return x}}catch(e){} return {plans:clone(defaults),history:{},dark:false,timerEnabled:true,selectedDate:todayISO(),copiedPlan:null,copiedDay:''}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function todayISO(){return new Date().toISOString().slice(0,10)}
function dayIndex(date){let d=new Date(date+'T12:00:00').getDay();return (d+6)%7}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function clone(x){return JSON.parse(JSON.stringify(x))}
function fmtPause(x){return x.pauseValue+' '+(x.pauseUnit==='sec'?'s':'min')}
function isComplete(date,di){const rec=state.history[date]?.[di];const plan=state.plans[di]||[];return plan.length>0&&plan.every((e,i)=>rec?.[i]?.length>=e.sets)}
function isStarted(date,di){const rec=state.history[date]?.[di];return !!(rec&&Object.keys(rec).length)}
function render(){document.body.classList.toggle('dark',state.dark);const di=dayIndex(state.selectedDate);const plan=state.plans[di]||[];let cur=Number((()=>{try{return sessionStorage.getItem('currentEx')||0}catch(e){return 0}})());if(cur>=plan.length)cur=0;try{sessionStorage.setItem('currentEx',cur)}catch(e){}const ex=plan[cur];
let h=`<div class="title">MŮJ TRÉNINK</div><div class="subtitle">VÁHA • x • VÝVOJ</div>`;
h+=`<div class="row"><div class="label">TRÉNINK</div><button class="valueBtn grow">${DAYS[di]}</button></div>`;
h+=`<div class="row"><div class="label">DATUM</div><input id="date" class="dateBtn grow" type="date" value="${state.selectedDate}"></div>`;
h+=`<button class="blue full" id="start">📅 ZAHÁJIT TRÉNINK</button><div class="sectionGap"></div>`;
h+=`<div class="row"><div class="label">CVIK</div><select id="exerciseSelect" class="valueBtn grow">${plan.map((e,i)=>`<option value="${i}" ${i===cur?'selected':''}>${esc(e.name)} ${isComplete(state.selectedDate,di)?'✓':''}</option>`).join('')||'<option>Žádný cvik</option>'}</select></div>`;
h+=`<div class="exercisePos">${ex?`CVIK ${cur+1} / ${plan.length}`:''}</div><div class="exerciseName">${ex?esc(ex.name):'Žádný cvik'}</div><div class="exerciseInfo">${ex?`${ex.sets} sérií • pauza ${fmtPause(ex)}`:''}</div>`;
if(ex){const rec=state.history[state.selectedDate]?.[di]?.[cur]||[];const done=rec.length>=ex.sets;h+=`<div class="status ${done?'ok':'bad'}">${done?'✓ SPLNĚNO':'• NEDOKONČENO'}</div>`;h+=`<div id="sets">${Array.from({length:ex.sets},(_,i)=>{const v=rec[i]||{};return `<div class="setBox"><div class="setTitle">SÉRIE ${i+1}</div><div class="setRow"><label>VÁHA (kg)<input inputmode="decimal" data-set="${i}" data-field="weight" value="${esc(v.weight??'')}"></label><label>OPAKOVÁNÍ<input inputmode="numeric" data-set="${i}" data-field="reps" value="${esc(v.reps??'')}"></label></div><button class="blue wide" data-save-set="${i}">ULOŽIT SÉRII</button></div>`}).join('')}</div>`}
h+=`<div id="timer" class="timer"><div id="timerText" class="time">00:00</div><button class="ghost" id="skip">PŘESKOČIT</button></div><div class="note"></div>`;
h+=`<div class="actions"><button class="blue" id="prev">‹ PŘEDCHOZÍ CVIK</button><button class="blue" id="next">DALŠÍ CVIK ›</button></div>`;
h+=`<div class="actions"><button class="blue" id="edit">✎ UPRAVIT PLÁN</button><button class="blue" id="history">HISTORIE / STATISTIKY</button></div>`;
h+=`<div class="actions"><button class="blue" id="backup">ZÁLOHA</button><button class="blue" id="theme">SVĚTLÝ / TMAVÝ</button></div>`;
h+=`<button class="blue wide" id="timerSetting">ČASOVAČ: ${state.timerEnabled?'ZAPNUTO':'VYPNUTO'}</button>`;
document.getElementById('app').innerHTML=h;bindMain(di,cur);}
function bindMain(di,cur){document.getElementById('date').onchange=e=>{state.selectedDate=e.target.value||todayISO();save();render()};document.getElementById('start').onclick=()=>{state.selectedDate=todayISO();save();render()};const sel=document.getElementById('exerciseSelect');if(sel)sel.onchange=()=>{try{sessionStorage.setItem('currentEx',sel.value)}catch(e){}render()};document.getElementById('prev').onclick=()=>{if(cur>0){sessionStorage.setItem('currentEx',cur-1);render()}};document.getElementById('next').onclick=()=>{if(cur<state.plans[di].length-1){sessionStorage.setItem('currentEx',cur+1);render()}};document.getElementById('edit').onclick=showEditor;document.getElementById('history').onclick=showHistory;document.getElementById('backup').onclick=backupMenu;document.getElementById('theme').onclick=()=>{state.dark=!state.dark;save();render()};document.getElementById('timerSetting').onclick=()=>{state.timerEnabled=!state.timerEnabled;save();if(!state.timerEnabled)stopTimer();render()};document.querySelectorAll('[data-save-set]').forEach(b=>b.onclick=()=>saveSet(di,cur,Number(b.dataset.saveSet)));}
function saveSet(di,cur,i){const box=document.querySelector(`.setBox:nth-child(${i+1})`);const w=box.querySelector('[data-field="weight"]').value.trim();const r=box.querySelector('[data-field="reps"]').value.trim();if(!w||!r){alert('Zadej váhu a opakování.');return}state.history[state.selectedDate]??={};state.history[state.selectedDate][di]??={};state.history[state.selectedDate][di][cur]??=[];state.history[state.selectedDate][di][cur][i]={weight:w,reps:r};save();render();if(state.timerEnabled&&i<state.plans[di][cur].sets-1)startTimer(state.plans[di][cur].pauseValue,state.plans[di][cur].pauseUnit)}
let timerId=null;function startTimer(v,u){stopTimer();let sec=v*(u==='sec'?1:60);if(sec<=0)return;document.getElementById('timer').style.display='flex';const out=document.getElementById('timerText');const tick=()=>{out.textContent=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');if(sec<=0){stopTimer();beep();return}sec--;timerId=setTimeout(tick,1000)};tick()}function stopTimer(){if(timerId)clearTimeout(timerId);timerId=null;const t=document.getElementById('timer');if(t)t.style.display='none'}function beep(){try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=880;g.gain.value=.08;o.start();setTimeout(()=>{o.stop();c.close()},250)}catch(e){}}document.addEventListener('click',e=>{if(e.target.id==='skip')stopTimer()});
function showEditor(){const di=dayIndex(state.selectedDate);openEditor(di,clone(state.plans[di]))}
function openEditor(di,working){const root=document.getElementById('modalRoot');root.innerHTML=`<div class="modalBack"><div class="modal lightEditor"><div class="modalHead">UPRAVIT ${DAYS[di]}</div><div id="editorList" class="modalScroll"></div><div class="modalButtons"><button class="blue" id="copyPlan">KOPÍROVAT PLÁN</button><button class="blue" id="pastePlan">VLOŽIT PLÁN</button></div><div class="modalScroll" style="overflow:visible"><button class="blue wide" id="addExercise">+ PŘIDAT CVIK</button></div><div class="editorBottom"><button class="blue" id="backEdit">ZPĚT</button><button class="blue" id="saveEdit">ULOŽIT ZMĚNY</button></div></div></div>`;const list=document.getElementById('editorList');function rebuild(){list.innerHTML=working.map((e,i)=>`<div class="editorCard" data-i="${i}"><div class="cvik">CVIK ${i+1}</div><input class="editorInput name" value="${esc(e.name)}"><div class="editorGrid"><div class="editorLabel">SÉRIE</div><input class="editorInput sets" inputmode="numeric" value="${e.sets}"></div><div class="pauseGrid"><div class="editorLabel">PAUZA</div><input class="editorInput pause" inputmode="numeric" value="${e.pauseValue}"><div class="unitBox"><div class="unitLabel">ČAS</div><select class="unitSelect"><option value="min" ${e.pauseUnit==='min'?'selected':''}>minuty</option><option value="sec" ${e.pauseUnit==='sec'?'selected':''}>sekundy</option></select></div></div><div class="editorBtns"><button class="blue up">↑</button><button class="blue down">↓</button><button class="blue del">SMAZAT</button></div></div>`).join('');list.querySelectorAll('.editorCard').forEach(card=>{const i=+card.dataset.i;card.querySelector('.up').onclick=()=>{syncEditor();if(i>0){[working[i-1],working[i]]=[working[i],working[i-1]];rebuild()}};card.querySelector('.down').onclick=()=>{syncEditor();if(i<working.length-1){[working[i+1],working[i]]=[working[i],working[i+1]];rebuild()}};card.querySelector('.del').onclick=()=>{syncEditor();working.splice(i,1);rebuild()}})}rebuild();function syncEditor(){document.querySelectorAll('.editorCard').forEach(card=>{const i=+card.dataset.i;working[i].name=clean(card.querySelector('.name').value);working[i].sets=Math.max(1,Math.min(10,parseInt(card.querySelector('.sets').value)||1));working[i].pauseValue=Math.max(0,parseInt(card.querySelector('.pause').value)||0);working[i].pauseUnit=card.querySelector('.unitSelect').value})}
function close(){root.innerHTML=''}document.getElementById('backEdit').onclick=close;document.getElementById('saveEdit').onclick=()=>{syncEditor();state.plans[di]=clone(working);save();close();render()};document.getElementById('copyPlan').onclick=()=>{syncEditor();state.copiedPlan=clone(working);state.copiedDay=DAYS[di];save();alert('Plán '+DAYS[di]+' zkopírován.')};document.getElementById('pastePlan').onclick=()=>{if(!state.copiedPlan){alert('Nejdříve zkopíruj některý plán.');return}if(confirm('Nahradit plán pro '+DAYS[di]+' plánem z '+state.copiedDay+'?')){working=clone(state.copiedPlan);rebuild()}};document.getElementById('addExercise').onclick=()=>addExerciseDialog(working,rebuild)}
function clean(s){return String(s).replace(/[;|\n]/g,' ').trim()}
function addExerciseDialog(working,rebuild){const r=document.getElementById('modalRoot');r.insertAdjacentHTML('beforeend',`<div class="modalBack" id="addModal"><div class="modal" style="max-width:520px"><div class="modalHead">PŘIDAT CVIK</div><div class="dialog"><label>NÁZEV CVIKU</label><input id="newName" autocomplete="off" inputmode="text" lang="cs"><label>SÉRIE</label><input id="newSets" inputmode="numeric" value="3"><label>PAUZA</label><div class="pauseGrid"><div></div><input id="newPause" inputmode="numeric" value="2"><select id="newUnit"><option value="min">minuty</option><option value="sec">sekundy</option></select></div></div><div class="modalButtons"><button class="ghost" id="cancelAdd">ZRUŠIT</button><button class="blue" id="confirmAdd">PŘIDAT</button></div></div></div>`);document.getElementById('cancelAdd').onclick=()=>document.getElementById('addModal').remove();document.getElementById('confirmAdd').onclick=()=>{const name=clean(document.getElementById('newName').value);if(!name){alert('Zadej název cviku.');return}working.push({name,sets:Math.max(1,Math.min(10,parseInt(document.getElementById('newSets').value)||3)),pauseValue:Math.max(0,parseInt(document.getElementById('newPause').value)||0),pauseUnit:document.getElementById('newUnit').value});document.getElementById('addModal').remove();rebuild()};document.getElementById('newName').focus()}
function showHistory(){const r=document.getElementById('modalRoot');let dates=Object.keys(state.history).sort().reverse();let html=`<div class="modalBack"><div class="modal"><div class="modalHead">HISTORIE / STATISTIKY</div><div class="modalScroll">${dates.length?dates.map(d=>{const out=[];for(let di=0;di<7;di++){const rec=state.history[d]?.[di];if(!rec)continue;const plan=state.plans[di]||[];Object.keys(rec).forEach(i=>{const e=plan[i];if(e)out.push(`<div class="historyItem"><b>${DAYS[di]} – ${esc(e.name)}</b><br>${rec[i].map((s,k)=>`Série ${k+1}: ${esc(s.weight)} kg × ${esc(s.reps)}`).join(' • ')}</div>`)});}return `<div class="historyDay"><div class="historyTitle">${d}</div>${out.join('')||'Bez záznamu'}</div>`}).join(''):'<p>Historie je zatím prázdná.</p>'}<hr><h3>KALENDÁŘ</h3>${calendarHtml()}<h3>STATISTIKY</h3>${statsHtml()}</div><div class="editorBottom"><button class="blue" id="closeHistory">ZAVŘÍT</button><button class="blue" id="deleteHistory">SMAZAT HISTORII</button></div></div></div>`;r.innerHTML=html;document.getElementById('closeHistory').onclick=()=>r.innerHTML='';document.getElementById('deleteHistory').onclick=()=>{if(confirm('Smazat celou historii?')){state.history={};save();showHistory()}}};r.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{state.selectedDate=b.dataset.date;save();r.innerHTML='';render()})
function calendarHtml(){const d=new Date(state.selectedDate+'T12:00:00');const y=d.getFullYear(),m=d.getMonth();const first=new Date(y,m,1).getDay();const offset=(first+6)%7;let out='<div class="calendar">'+['Po','Út','St','Čt','Pá','So','Ne'].map(x=>`<div class="calHead">${x}</div>`).join('');const days=new Date(y,m+1,0).getDate();for(let i=0;i<offset;i++)out+='<div></div>';for(let n=1;n<=days;n++){const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`;const di=dayIndex(iso);let c='calDay';if(iso===todayISO())c+=' today';if(isComplete(iso,di))c+=' done';else if(isStarted(iso,di))c+=' started';out+=`<button class="${c}" data-date="${iso}">${n}${isComplete(iso,di)?' ✓':isStarted(iso,di)?' •':''}</button>`}return out+'</div>'}
function statsHtml(){const totals={};Object.keys(state.history).forEach(d=>{for(let di=0;di<7;di++){const rec=state.history[d]?.[di];const plan=state.plans[di]||[];if(!rec)continue;Object.keys(rec).forEach(i=>{const e=plan[i];if(!e)return;const key=e.name;totals[key]??={sessions:0,maxW:0,maxR:0};totals[key].sessions++;rec[i].forEach(s=>{totals[key].maxW=Math.max(totals[key].maxW,parseFloat(String(s.weight).replace(',','.'))||0);totals[key].maxR=Math.max(totals[key].maxR,parseInt(s.reps)||0)})})}});return Object.entries(totals).map(([n,x])=>`<div class="statCard"><b>${esc(n)}</b><div>Tréninky: ${x.sessions}</div><div>Max. váha: ${x.maxW} kg</div><div>Max. opakování: ${x.maxR}</div></div>`).join('')||'<p>Zatím nejsou statistická data.</p>'}
function backupMenu(){const r=document.getElementById('modalRoot');r.innerHTML=`<div class="modalBack"><div class="modal"><div class="modalHead">ZÁLOHA</div><div class="dialog"><p>Záloha je pouze v tomto zařízení. Export vytvoří soubor JSON, který můžeš později importovat.</p></div><div class="modalButtons"><button class="blue" id="export">EXPORT</button><button class="blue" id="import">IMPORT</button></div><div class="editorBottom"><button class="blue" id="closeB">ZAVŘÍT</button></div></div></div>`;document.getElementById('closeB').onclick=()=>r.innerHTML='';document.getElementById('export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='muj-trenink-zaloha.json';a.click();URL.revokeObjectURL(a.href)};document.getElementById('import').onclick=()=>{const inp=document.createElement('input');inp.type='file';inp.accept='.json,application/json';inp.onchange=async()=>{try{const x=JSON.parse(await inp.files[0].text());if(!x.plans||!x.history)throw Error();state=x;save();r.innerHTML='';render();alert('Záloha obnovena.')}catch(e){alert('Neplatná záloha.')}};inp.click()}}
window.addEventListener('error',e=>{const a=document.getElementById('app');if(a&&!a.innerHTML.trim())a.innerHTML='<div style="padding:28px;font-family:Arial;color:#111"><h2>MŮJ TRÉNINK</h2><p>Aplikaci se nepodařilo spustit.</p><p style="font-size:13px">Zkus stránku obnovit.</p></div>'});window.addEventListener('load',()=>{try{render()}catch(e){const a=document.getElementById('app');a.innerHTML='<div style="padding:28px;font-family:Arial;color:#111"><h2>MŮJ TRÉNINK</h2><p>Chyba při spuštění aplikace.</p></div>';console.error(e)}});
